name: Run Falcon AI
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python 3. 11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging edge-tts
        pip install packaging
        pip install -r requirements.txt
    - name: Run Falcon.py
      run: python Falcon.py
